---
language: c

env:
  global:
    - secure: "Mzjl6hrF+tCaUH3rIrqkGEf8o/Id/4NwvkOk4Gee/l1CQt5pab+DYB1dUBePD4m7Po1xL/m1OYfA0g3nTi3z/7okTWkAUQsfAIDp8GHI5NwE1PLy8SHxOEwt2vzv3YBOhyX+3Q3CyPoATSRzxOZ5fcCqwV90axN5dvDAnUTxId4="
    - DESTINATION_REPO_SUBPATH="synthetos/synthetos.github.io"
    - SOURCE_HEX="firmware/tinyg/default/tinyg.hex"
    - DEST_FILE_TEMPLATE="binaries/tinyg-{BRANCH}-{VERSION}.{EXT}"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc gcc-4.8 g++-4.8 llvm-3.4-tools llvm-3.4
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - gcc --version
  - g++ --version
  - export PATH=$PATH:/usr/lib/llvm-3.4/bin

script: "(cd firmware/tinyg/default && make ) && ( cd firmware/tinyg/sim && make && ./test.sh )"

#after_success:
#  - cd ../../.. && ./support/travis-push.py
